version: "3.8"

services:
  server: 
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: nginx
    ports: 
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: blog_db
    env_file:
      - ./env/mysql.env
    ports:
      - 3308:3308
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:latest
    container_name: npm
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
